//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuletaAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apuesta
    {
        public int IdApuesta { get; set; }
        public int NumeroApuesta { get; set; }
        public string ColorApuesta { get; set; }
        public decimal ValorApuesta { get; set; }
        public int IdUsuarioApuesta { get; set; }
        public int IdRuleta { get; set; }
    
        public virtual Ruleta Ruleta { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
