//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuletaAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruleta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ruleta()
        {
            this.Apuesta = new HashSet<Apuesta>();
        }
    
        public int IdRuleta { get; set; }
        public bool Estado { get; set; }
        public string Apertura { get; set; }
        public string Cierre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apuesta> Apuesta { get; set; }
    }
}
